2023 Update
Team537/RobotCode2023 pull request #2
Opened 2023-01-10 03:43 UTC by Asingh11771

Update to new WPILIB

2023-01-11 01:24 UTC, alwick requested changes

2023-01-11 01:24 UTC, alwick commented on src/main/java/frc/robot/commands/toggleFastMode.java
> +  /** Creates a new toggleFastModer. */
Classes should always start with Cap.

2023-01-11 01:24 UTC, alwick commented on src/main/java/frc/robot/commands/toggleSlowMode.java
> +  /** Creates a new toggleFastModer. */
Classes start with cap.

2023-01-18 01:04 UTC, arovge commented on README.md
> -# RobotCode2023
We can keep this if you want - could maybe include some info on the robot and such towards the end of the season

2023-01-18 01:04 UTC, arovge commented on src/main/java/frc/robot/Constants.java
> +  public static class VisionConstants {
Could move this to a separate file - maybe make a `constants` folder and make a `constants/VisionConstants.java` file in it. Would help quickly finding the constant you want to tweak instead of having a file with a few hundred lines you need to scan through

2023-01-18 01:04 UTC, arovge commented on src/main/java/frc/robot/RobotContainer.java
> +  private final DriveSubsystem m_robotDrive = new DriveSubsystem();
I made this comment when I was porting the wiki over to github: https://github.com/Team537/frc-wiki/pull/1#discussion_r1055962519

I don't mind if y'all want to keep using `m_*` or `k*` when writing code since a lot of the WPILIB code has it built in, but I think it takes away from readability

2023-01-18 01:04 UTC, arovge commented on src/main/java/frc/robot/RobotContainer.java
>    XboxController m_driverController2 = new XboxController(OIConstants.kDriverControllerPort);
Be consistent with access modifiers - some of these have `private` and some don't have any modifier

2023-01-18 01:04 UTC, arovge commented on src/main/java/frc/robot/RobotContainer.java
> +    boolean toggleSlowMode = true;
I think these vars and the forwardSpeed / turnSpeed should be in DriveSubsystem - it's implementation details of the drive subsystem

2023-01-18 01:04 UTC, arovge commented on src/main/java/frc/robot/RobotContainer.java
> +      // new RunCommand(() ->
remove the commented out code - i guess it doesn't matter because this will change to be swerve drive but

2023-01-18 01:04 UTC, austinrovge commented on src/main/java/frc/robot/commands/toggleFastMode.java
> +    // Use addRequirements() here to declare subsystem dependencies.
Could remove these comments if you want - up to you

2023-01-18 01:04 UTC, austinrovge commented on src/main/java/frc/robot/subsystems/Camera.java
> +package frc.robot.subsystems;
Spacing is messed up in this file

2023-01-18 01:04 UTC, austinrovge commented on src/main/java/frc/robot/subsystems/DriveSubsystem.java
> +package frc.robot.subsystems;
Spacing messed up in this file & some extra comments you could get rid of (up to you)

2023-03-08 16:45 UTC, closed without merging